#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

/*
    Problem 1
    =========
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

                                                        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

/*
    It's a super slow solution altho the answer was properly acquired with it in the blink of an eye.
*/
bool isPrime(uint64_t number)
{
    uint8_t flag = 0;

    for (uint64_t i = 1; i < number / 2; i++)
    {
        if (number % i == 0)
        {
            flag++;
        }

        if (flag >= 2)
        {
            return false;
        }
    }

    return true;
}

uint64_t findHighestPrime(uint64_t number)
{
    uint64_t highestPrime = 1;

    for (uint64_t i = 1; i < number / 2; i++)
    {
        printf("I: %d\n", i);
        double fDivision = number / (double)i;
        uint64_t iDivision = number / i;

        if (fDivision == (double)iDivision && isPrime(i))
        {
            printf("fDivision: %f, iDivision: %llu\n", fDivision, iDivision);
            highestPrime = i;
        }
    }

    return highestPrime;
}

int main()
{
    uint64_t number = 600851475143;

    printf("Largest prime factor of %llu is %llu", number, findHighestPrime(number));

    return 0;
}